/**
 * The shell policy case table: what a generated game's shell guard answers for each command. Shared by
 * guard-core.test.mjs (the pure classifier) and shell-safety.test.mjs (the Claude Code + Cursor entry),
 * so the classifier and both protocols are held to the same cases.
 */

/** @type {[command: string, expected: 'deny' | 'ask' | 'allow'][]} */
export const SHELL_CASES = [
    ['git status', 'allow'],
    ['ls -la && npm run build', 'allow'],
    ['', 'allow'],
    ['git reset --hard', 'deny'],
    ['git reset --hard HEAD~1', 'deny'],
    ["git 'reset' --hard", 'deny'],
    ['git \\reset --hard', 'deny'],
    ['git -C game reset --hard', 'deny'],
    ['git --no-pager reset --hard', 'deny'],
    ['git reset --soft HEAD~1', 'allow'],
    ['git checkout -- src/game.js', 'deny'],
    ['git checkout "--" .', 'deny'],
    ['git checkout -b feature', 'allow'],
    ['git restore src/game.js', 'deny'],
    ['git restore .', 'deny'],
    ['git restore --staged src/game.js', 'allow'],
    ['git restore -S src/game.js', 'allow'],
    ['git restore --staged --worktree src/game.js', 'deny'],
    ['git restore -S -W src/game.js', 'deny'],
    ['git clean', 'deny'],
    ['git clean -fd', 'deny'],
    ['git clean -n', 'allow'],
    ['git clean --dry-run', 'allow'],
    ['git clean -nfd', 'deny'],
    ['git -c clean.requireForce=false clean -d', 'deny'],
    ['git clean -n && rm -f build.log', 'allow'],
    ['git push', 'allow'],
    ['git push origin foo-feature', 'allow'],
    ['git push --force', 'ask'],
    ['git push -f origin main', 'ask'],
    ['git push --force-with-lease=main origin main', 'ask'],
    ['git push origin +main', 'ask'],
    ['git push --force>out.log', 'ask'],
    ['git branch -D old', 'ask'],
    ['git branch -Dq old', 'ask'],
    ['git branch --delete --force old', 'ask'],
    ['git branch -d old', 'allow'],
    ['git branch --delete old', 'allow'],
    ['git stash drop', 'ask'],
    ['git stash clear', 'ask'],
    ['git stash pop', 'allow'],
    ['echo hi\ngit reset --hard', 'deny'],
    ['git clean -fd\ngit clean -n', 'deny'],
    ['git status\ngit push --force', 'ask'],
];
