import { describe, test } from 'node:test';
import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const CONTENT_DIR = fileURLToPath(new URL('../../content/', import.meta.url));
const DESCRIPTION_MAX_LENGTH = 160;

// Hand-authored pages, per packages/website/CLAUDE.md's "What is hand-authored and what is generated" section.
// content/blog/** is added dynamically below via listBlogPosts(); everything else hand-authored is a fixed,
// known set, so it is listed explicitly rather than globbed.
//
// content/docs/<section>/<topic>.mdx is deliberately NOT included: those pages are generated by
// scripts/sync-docs-from-engine.mjs, and their description comes from the `subtitle` field in
// packages/blit386/docs/_sitemap.json. A length violation there is not fixable by editing anything under
// content/ – the fix belongs in the engine package's sitemap manifest – so folding those pages into this
// assertion would point a contributor at the wrong repository and the wrong file. A guard for the sitemap's
// own subtitles, if wanted, belongs in packages/blit386 against _sitemap.json directly, not here.
const HAND_AUTHORED_PAGES = [
    'index.mdx',
    'showcase.mdx',
    'community.mdx',
    'mcp-server.mdx',
    'docs/index.mdx',
    'docs/getting-started.mdx',
    'docs/faq.mdx',
];

const listBlogPosts = async () => {
    const entries = await readdir(`${CONTENT_DIR}blog/`);
    return entries.filter((name) => name.endsWith('.mdx')).map((name) => `blog/${name}`);
};

/**
 * Extracts frontmatter fields from an MDX file's leading `---` block. A value can sit on the `key:` line
 * itself, or – as this repo's authors write longer descriptions – as indented continuation lines below a
 * bare `key:`, which YAML folds into one space-joined string; this mirrors that folding.
 *
 * @param {string} contents
 * @returns {Record<string, string>}
 */
const parseFrontmatter = (contents) => {
    const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(contents);
    if (!match) return {};

    /** @type {Record<string, string>} */
    const fields = {};
    /** @type {string | null} */
    let currentKey = null;
    /** @type {string[]} */
    let currentLines = [];

    const flush = () => {
        if (currentKey) fields[currentKey] = currentLines.join(' ').trim();
        currentLines = [];
    };

    for (const line of (match[1] ?? '').split(/\r?\n/)) {
        const keyMatch = /^([A-Za-z_][\w-]*):\s?(.*)$/.exec(line);

        if (keyMatch) {
            flush();
            currentKey = keyMatch[1] ?? null;
            const inlineValue = (keyMatch[2] ?? '').trim();
            currentLines = inlineValue ? [inlineValue] : [];
        } else if (currentKey) {
            currentLines.push(line.trim());
        }
    }

    flush();

    return fields;
};

const pages = [...HAND_AUTHORED_PAGES, ...(await listBlogPosts())];

describe('page description length', () => {
    for (const relativePath of pages) {
        test(`content/${relativePath} has a description under ${DESCRIPTION_MAX_LENGTH} characters`, async () => {
            const contents = await readFile(`${CONTENT_DIR}${relativePath}`, 'utf8');
            const { description } = parseFrontmatter(contents);

            assert.ok(description, `content/${relativePath}: description is missing or empty`);

            assert.ok(
                description.length <= DESCRIPTION_MAX_LENGTH,
                `content/${relativePath}: description is ${description.length} characters, exceeds the ${DESCRIPTION_MAX_LENGTH}-character ceiling`,
            );
        });
    }
});
