// Bootstrap core: the install-then-checkup both Node bootstrap entries run. Source: @blit386/kit
// (generated by `npx blit agents sync`). antigravity-bootstrap.cjs runs it once per conversation and
// copilot-hook.cjs on every session start; session-start.sh is the same sequence for the agents that
// run hooks through `sh`. This file only does the work and returns the report lines - when it runs
// and how the report reaches the assistant belong to each entry. A failed install is reported, not
// thrown, so an entry never has to catch anything here to keep its session alive.
// .cjs so it stays CommonJS when a parent package.json sets "type": "module".

const { spawnSync } = require('node:child_process');
const { existsSync } = require('node:fs');
const path = require('node:path');

/**
 * Install dependencies when `node_modules` is missing, then run `blit doctor` when the CLI is installed.
 *
 * @param {string} root - The project root; every command runs there.
 * @param {string} install - The package manager's install command (`npm install`, `pnpm install`, ...).
 * @returns {string[]} One report line per step taken, in order; empty when there was nothing to do.
 */
function bootstrapReport(root, install) {
    const run = (command) =>
        spawnSync(command, { cwd: root, shell: true, encoding: 'utf8', windowsHide: true, timeout: 280_000 });
    const report = [];

    if (!existsSync(path.join(root, 'node_modules'))) {
        const result = run(install);

        report.push(
            result.status === 0
                ? `[session-start] Installed dependencies with \`${install}\`.`
                : `[session-start] \`${install}\` failed; continuing without a warmed toolchain.`,
        );
    }

    // Relative, resolved against `cwd` by the shell: a path.join keeps the separators Windows shells accept.
    const blit = path.join('node_modules', '.bin', 'blit');

    if (existsSync(path.join(root, blit))) {
        const doctor = run(`${blit} doctor`);

        report.push(`[session-start] blit doctor:\n${`${doctor.stdout}${doctor.stderr}`.trim()}`);
    }

    return report;
}

module.exports = { bootstrapReport };
