// Guard core: the protect-files and dangerous-shell classification every agent's hook entry shares.
// Source: @blit386/kit (generated by `npx blit agents sync`).
// .cjs so it stays CommonJS when a parent package.json sets "type": "module".
//
// The two classifiers are pure: they take a path or a command string and return a verdict or null.
// Everything agent-specific - where the path or command sits in the payload, and how a block is
// reported (exit code 2, a JSON decision, a thrown error) - belongs in each agent's entry script,
// so these functions never see a protocol. `failClosed` + `parsePayload` are the shared wrapper:
// an entry that cannot read its request blocks it instead of letting it through, because several
// agents treat a crashed hook as "allow".
//
// Decision (BT-564, BT-576): the shell classification is a Node port of the kit's former
// shell-safety.sh, so no agent's entry needs `sh` or `python3` (neither is on every hook PATH;
// Windows has no `sh`). Claude Code and Cursor share one entry over it, shell-safety.cjs.
// Antigravity's entry (antigravity-guard.cjs) runs the same port.

const path = require('node:path');

/** Lock files that do not end in `.lock`. Any `*.lock` file (yarn.lock, bun.lock, ...) is caught by its suffix. */
const LOCK_FILES = new Set(['package-lock.json', 'pnpm-lock.yaml', 'bun.lockb']);

/** `.env` and `.env.local`, but not `.env.example` - that one is a template meant to be edited. */
const isEnvFile = (name) => (name === '.env' || name.startsWith('.env.')) && name !== '.env.example';

/**
 * Should an assistant be kept from editing this file? A lock file is written by the package manager (an
 * install rewrites it correctly; a hand edit breaks the next install). A .env file holds secrets.
 *
 * @param {string} file - The path the assistant wants to edit.
 * @returns {{ message: string } | null} Why the edit is blocked, or null to allow it.
 */
function isProtectedPath(file) {
    const name = path.basename(file);

    if (name.endsWith('.lock') || LOCK_FILES.has(name)) {
        return {
            message: `${name} is written by the package manager. Change package.json and run an install instead.`,
        };
    }

    if (isEnvFile(name)) {
        return { message: `${name} holds secrets. Ask the user to edit it by hand.` };
    }

    return null;
}

// The POSIX space and alphanumeric classes, spelled out so the port matches what grep -E matched.
const SPACE = '[ \\t\\v\\f\\r]';
const NON_SPACE = '[^ \\t\\v\\f\\r]';
const ALPHANUMERIC = '[A-Za-z0-9]';
// Where an argument ends: whitespace, a shell separator or redirection, or the end of the line.
const ARG_END = `(${SPACE}|[;&|<>]|$)`;
// Any earlier arguments of the same command (the scan stops at a separator, so a later command's flags
// never count), then the space before the flag being looked for.
const ARGS = `(${SPACE}+[^ \\t\\v\\f\\r;&|<>]+)*${SPACE}+`;

// `git` plus any global options (`-C dir`, `-c key=value`, `--no-pager`) before the subcommand. Written so
// a backtracking engine cannot go exponential on a long run of options: one `-\S+` branch covers short and
// long options alike, and an option value may not start with whitespace, so it cannot swallow the next option.
const GIT_PREFIX = `git(${SPACE}+-${NON_SPACE}+(${SPACE}+[^- \\t\\v\\f\\r]${NON_SPACE}*)?)*${SPACE}+`;

const RESET_OR_CHECKOUT = new RegExp(`${GIT_PREFIX}reset${SPACE}+--hard|${GIT_PREFIX}checkout${SPACE}+--`);
const CLEAN = new RegExp(`${GIT_PREFIX}clean${ARG_END}`);
const CLEAN_FORCE = new RegExp(`${GIT_PREFIX}clean${ARGS}(-${ALPHANUMERIC}*f${ALPHANUMERIC}*|--force)${ARG_END}`);
const CLEAN_DRY_RUN = new RegExp(`${GIT_PREFIX}clean${ARGS}(-${ALPHANUMERIC}*n${ALPHANUMERIC}*|--dry-run)${ARG_END}`);
const RESTORE = new RegExp(`${GIT_PREFIX}restore${ARG_END}`);
const RESTORE_STAGED = new RegExp(`${GIT_PREFIX}restore${ARGS}(-S|--staged)${ARG_END}`);
const RESTORE_WORKTREE = new RegExp(`${GIT_PREFIX}restore${ARGS}(-W|--worktree)${ARG_END}`);
const FORCE_PUSH = new RegExp(
    `${GIT_PREFIX}push((${SPACE}+${NON_SPACE}+)*${SPACE}+(-f|--force|--force-with-lease(=${NON_SPACE}*)?)${ARG_END}|(${SPACE}+${NON_SPACE}+)*${SPACE}+\\+${NON_SPACE}+)`,
);
const BRANCH = new RegExp(`${GIT_PREFIX}branch${ARG_END}`);
const BRANCH_SHORT_D = new RegExp(`${GIT_PREFIX}branch${ARGS}-${ALPHANUMERIC}*D${ALPHANUMERIC}*${ARG_END}`);
const BRANCH_LONG_DELETE = new RegExp(`${GIT_PREFIX}branch${ARGS}--delete${ARG_END}`);
const BRANCH_LONG_FORCE = new RegExp(`${GIT_PREFIX}branch${ARGS}(-f|--force)${ARG_END}`);
const STASH_DROP_CLEAR = new RegExp(`${GIT_PREFIX}stash${SPACE}+(drop|clear)${ARG_END}`);

const DENY_DESTRUCTIVE = {
    decision: 'deny',
    userMessage: 'Blocked a destructive git command that could lose your game changes.',
    agentMessage: 'Use safer git operations. Ask the user before discarding any work.',
};
const ASK_FORCE_PUSH = {
    decision: 'ask',
    userMessage: 'Force push detected. Confirm before continuing.',
    agentMessage: 'Force push rewrites history. Ask the user for explicit confirmation first.',
};
const ASK_BRANCH_DELETE = {
    decision: 'ask',
    userMessage: 'Force branch delete detected (git branch -D). Confirm before continuing.',
    agentMessage: 'git branch -D permanently deletes an unmerged branch. Ask the user for explicit confirmation first.',
};
const ASK_STASH = {
    decision: 'ask',
    userMessage: 'Stash drop/clear detected. Confirm before continuing.',
    agentMessage:
        'git stash drop/clear permanently discards stashed work. Ask the user for explicit confirmation first.',
};

/**
 * Classify a shell command the assistant wants to run. Two tiers, split by whether git itself can still recover
 * what the command would discard:
 *
 * - Deny (no override): `git reset --hard`, `git checkout --`, `git restore` in any form that touches the worktree,
 *   and `git clean` unless it is a dry run with no force flag. Each destroys content no git object was ever
 *   created for (uncommitted changes, untracked files), so no approval after the fact can bring it back.
 *   `git restore --staged` without `--worktree` only resets the index and leaves the files alone, so it is the
 *   one safe restore. `git clean` is denied by default rather than by force flag, because
 *   `git -c clean.requireForce=false clean -d` deletes without naming one.
 * - Ask (an explicit approval lets it through): `git push --force*` or a `+refspec`, `git branch -D`, and
 *   `git stash drop/clear`. These can discard work too, but reflog (or the remote's) keeps the commits reachable
 *   for a while, so approving one is not approving something irreversible.
 *
 * `git checkout --` and `git restore` are two spellings of one operation and must stay in the same tier (BT-413).
 *
 * @param {string} command - The raw command text.
 * @returns {{ decision: 'deny' | 'ask', userMessage: string, agentMessage: string } | null} The verdict, or null to allow.
 */
function isDangerousCommand(command) {
    // Quotes and backslashes are dropped first, so `git "reset" --hard` and `git \reset --hard` cannot dodge
    // the word checks. Each check asks "does any line match", so a multi-line command is caught on any line.
    const lines = command.replace(/['"\\]/g, '').split('\n');
    const any = (pattern) => lines.some((line) => pattern.test(line));

    const destructiveClean = any(CLEAN) && (any(CLEAN_FORCE) || !any(CLEAN_DRY_RUN));
    const destructiveRestore = any(RESTORE) && (!any(RESTORE_STAGED) || any(RESTORE_WORKTREE));

    if (any(RESET_OR_CHECKOUT) || destructiveClean || destructiveRestore) {
        return DENY_DESTRUCTIVE;
    }

    if (any(FORCE_PUSH)) {
        return ASK_FORCE_PUSH;
    }

    if (any(BRANCH) && (any(BRANCH_SHORT_D) || (any(BRANCH_LONG_DELETE) && any(BRANCH_LONG_FORCE)))) {
        return ASK_BRANCH_DELETE;
    }

    if (any(STASH_DROP_CLEAR)) {
        return ASK_STASH;
    }

    return null;
}

/**
 * Parse a hook payload. Throws - so `failClosed` turns it into a deny - unless the text is a JSON object.
 * A leading UTF-8 BOM is dropped first: Cursor on Windows prefixes one.
 *
 * @param {string} text - The raw payload.
 * @returns {Record<string, unknown>} The parsed object.
 */
function parsePayload(text) {
    const payload = JSON.parse(text.replace(/^\uFEFF/, ''));

    if (typeof payload !== 'object' || payload === null || Array.isArray(payload)) {
        throw new Error('the hook payload is not a JSON object');
    }

    return payload;
}

/** What a guard that could not read its request answers. */
const UNREADABLE = {
    decision: 'deny',
    message: 'The guard could not read the request, so it was blocked.',
};

/**
 * Run a guard so that it fails closed: any error thrown while reading or classifying the request
 * becomes a deny instead of an allow.
 *
 * @template T
 * @param {() => T} check - Reads the request and returns a verdict, or null to allow.
 * @returns {T | typeof UNREADABLE} The verdict, null, or the deny for an unreadable request.
 */
function failClosed(check) {
    try {
        return check();
    } catch {
        return UNREADABLE;
    }
}

module.exports = { failClosed, isDangerousCommand, isProtectedPath, parsePayload, UNREADABLE };
