// OpenCode plugin from @blit386/kit (generated by `npx blit agents sync`; your edits are flagged on sync).
//
// OpenCode runs every file in .opencode/plugins/ the moment it opens this folder, with no trust prompt, so here is
// everything this one does - nothing else. It makes no network calls itself (step 2 may, through your package
// manager):
//
//   1. Before each tool call it asks the guard core (.opencode/hooks/guard-core.cjs) two questions and blocks the
//      call by throwing when the answer is no: is this shell command a destructive git command (reset --hard,
//      checkout --, restore, clean), and is this edit aimed at a lock file or a .env file? If it cannot read the
//      request, it blocks. opencode.json holds the same rules as a permission list; this adds what a list of
//      patterns cannot catch, like `bash -c "git reset --hard"` or an edit made through a patch.
//   2. When you open a session (not a subagent's) it runs .opencode/hooks/session-start.sh, which installs
//      dependencies if they are missing and runs `blit doctor`. Output is discarded and a failure never stops the
//      session.
//
// The "ask first" commands (force push, branch -D, stash drop) are left to the permission list in opencode.json,
// because a plugin can only block, not ask.

import guardCore from '../hooks/guard-core.cjs';

const { failClosed, isDangerousCommand, isProtectedPath } = guardCore;

/** Tools that write files. `apply_patch` and `patch` name their files inside the patch text instead of `filePath`. */
const EDIT_TOOLS = new Set(['edit', 'write', 'multiedit']);
const PATCH_TOOLS = new Set(['apply_patch', 'patch']);

/**
 * The file lines of a patch: `*** Update File: path`, `*** Add File: path`, `*** Delete File: path`, `*** Move to: path`.
 * Matches OpenCode's own parser, which takes everything after the colon and trims it, so the space is optional here
 * too (`*** Update File:.env` is a valid header). Leading whitespace is tolerated, which OpenCode does not need, so
 * this can only ever see more files than it does.
 */
const PATCH_FILE_LINE = /^\s*\*\*\* (?:Add File|Update File|Delete File|Move to):(.*)$/gm;

/** Every file a tool call would write, or throws when there is none to find (so the guard fails closed). */
function editedFiles(tool, args) {
    if (PATCH_TOOLS.has(tool)) {
        const files = [...args.patchText.matchAll(PATCH_FILE_LINE)]
            .map((match) => match[1].trim())
            .filter((file) => file !== '');

        if (files.length === 0) {
            throw new Error('the patch names no file');
        }

        return files;
    }

    if (typeof args.filePath !== 'string' || args.filePath === '') {
        throw new Error('the edit names no file');
    }

    return [args.filePath];
}

/** The verdict for one tool call: null to allow it, otherwise something with a message. */
function classifyCall(tool, args) {
    if (tool === 'bash') {
        if (typeof args.command !== 'string') {
            throw new Error('the shell command is not text');
        }

        const verdict = isDangerousCommand(args.command);

        // `ask` verdicts are the permission list's job: a plugin can only block.
        return verdict?.decision === 'deny' ? { message: `${verdict.userMessage} ${verdict.agentMessage}` } : null;
    }

    if (EDIT_TOOLS.has(tool) || PATCH_TOOLS.has(tool)) {
        for (const file of editedFiles(tool, args)) {
            const verdict = isProtectedPath(file);

            if (verdict !== null) {
                return verdict;
            }
        }
    }

    return null;
}

export const KitGuard = async ({ $, directory }) => ({
    'tool.execute.before': async (input, output) => {
        const verdict = failClosed(() => classifyCall(input.tool, output.args));

        if (verdict !== null) {
            throw new Error(verdict.message);
        }
    },

    event: async ({ event }) => {
        // A subagent's session has a parent; only the session the person opened needs the bootstrap.
        if (event.type === 'session.created' && event.properties.info.parentID === undefined) {
            await $`sh .opencode/hooks/session-start.sh`
                .cwd(directory)
                .env({ ...process.env, BLIT_PM_INSTALL: '{{pmInstall}}' })
                .quiet()
                .throws(false);
        }
    },
});
