// Shell safety hook for Claude Code (PreToolUse) and Cursor (beforeShellExecution): blocks risky
// destructive git commands. Source: @blit386/kit (generated by `npx blit agents sync`).
// Also symlinked as this repo's own .cursor/hooks/shell-safety.cjs (with guard-core.cjs linked beside
// it, so the require below resolves next to the link too) - see .claude/hooks/shell-safety.sh
// for the separate maintainer copy this repo's own PreToolUse hook uses instead.
// .cjs so it stays CommonJS when a parent package.json sets "type": "module".
//
// The policy (which commands deny or ask, and why) lives in guard-core.cjs, shared with every other
// agent's entry; this file only knows the two payloads and protocols:
//   Claude - deny: agent message on stderr + exit 2; ask: permissionDecision JSON + exit 0; allow: exit 0
//   Cursor - {"permission":"allow"|"deny"|"ask","user_message","agent_message"} on stdout + exit 0
// Detection: only hook_event_name === "PreToolUse" means Claude, because Cursor also sends a
// hook_event_name (its own event name) and must always get JSON on stdout.
// Node only: no `sh` (absent from Cursor's Windows hook PATH) and no `python3`.

const { readFileSync } = require('node:fs');
const { failClosed, isDangerousCommand, parsePayload, UNREADABLE } = require('./guard-core.cjs');

/** The first non-empty `command` or `raw_command` string anywhere in the payload, depth first. */
function findCommand(node) {
    if (typeof node !== 'object' || node === null) {
        return '';
    }

    for (const key of ['command', 'raw_command']) {
        if (typeof node[key] === 'string' && node[key]) {
            return node[key];
        }
    }

    // Object.values walks an array's items and an object's values alike.
    for (const value of Object.values(node)) {
        const found = findCommand(value);
        if (found) {
            return found;
        }
    }

    return '';
}

const request = failClosed(() => {
    const payload = parsePayload(readFileSync(0, 'utf8'));

    return {
        isClaude: payload.hook_event_name === 'PreToolUse',
        verdict: isDangerousCommand(findCommand(payload)),
    };
});

// JSON.stringify drops the undefined messages, so an allow is just {"permission":"allow"}.
const cursorAnswer = (permission, userMessage, agentMessage) =>
    `${JSON.stringify({ permission, user_message: userMessage, agent_message: agentMessage })}\n`;

if (request === UNREADABLE) {
    // The agent cannot be told from an unreadable payload, so answer both ways. Cursor reads the JSON (and
    // its failClosed blocks on the non-zero exit anyway); Claude blocks on exit 2 with the stderr reason.
    process.stdout.write(cursorAnswer('deny', UNREADABLE.message, UNREADABLE.message));
    process.stderr.write(`${UNREADABLE.message}\n`);
    process.exit(2);
}

const { isClaude, verdict } = request;

if (isClaude) {
    if (verdict?.decision === 'deny') {
        // Exit 2 stderr is fed to the model, so use the agent-facing message.
        process.stderr.write(`${verdict.agentMessage}\n`);
        process.exit(2);
    }

    if (verdict?.decision === 'ask') {
        // permissionDecisionReason for "ask" is shown to the user in the permission UI.
        const answer = {
            hookSpecificOutput: {
                hookEventName: 'PreToolUse',
                permissionDecision: 'ask',
                permissionDecisionReason: verdict.userMessage,
            },
        };
        process.stdout.write(`${JSON.stringify(answer)}\n`);
    }

    process.exit(0);
}

process.stdout.write(cursorAnswer(verdict?.decision ?? 'allow', verdict?.userMessage, verdict?.agentMessage));
process.exit(0);
